import streamlit as st
api_key = st.secrets["OPENAI_API_KEY"]
from dotenv import load_dotenv
load_dotenv()
import os
import streamlit as st
from dotenv import load_dotenv
from groq import Groq
from typing import Dict, List
from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
import io

# Load environment variables
load_dotenv()
GROQ_API_KEY = os.getenv("GROQ_API_KEY")

@st.cache_resource
def get_groq_client_cached(api_key: str = None):
    api_key = api_key or GROQ_API_KEY
    if not api_key:
        st.warning("⚠️ Groq API key missing. Please set it in .env or Streamlit secrets.")
        return None
    return Groq(api_key=api_key)

def init_state():
    for key, default in {
        "messages": [],
        "user_name": "",
        "user_email": "",
        "debate_active": False,
        "debate_topic": "",
        "debate_style": "Formal",
        "conclusion": None,
        "is_processing": False,
    }.items():
        if key not in st.session_state:
            st.session_state[key] = default

def generate_pdf(messages: List[Dict[str, str]]) -> bytes:
    buffer = io.BytesIO()
    c = canvas.Canvas(buffer, pagesize=letter)
    width, height = letter
    y = height - 40

    c.setFont("Helvetica-Bold", 16)
    c.drawString(50, y, "Debate Transcript")
    y -= 40

    c.setFont("Helvetica", 12)
    for msg in messages:
        text = f"{msg['role'].capitalize()}: {msg['content']}"
        for line in text.split("\n"):
            wrapped_lines = [line[i:i+90] for i in range(0, len(line), 90)]
            for wrapped in wrapped_lines:
                if y < 40:
                    c.showPage()
                    c.setFont("Helvetica", 12)
                    y = height - 40
                c.drawString(50, y, wrapped)
                y -= 20

    c.drawString(50, 30, "Generated by Debate Partner Bot 🎤")
    c.save()
    buffer.seek(0)
    return buffer

@st.cache_data(show_spinner=False)
def generate_opposite_response_cached(api_key: str, user_message: str, style: str = "Formal"):
    client = get_groq_client_cached(api_key)
    if not client:
        return "⚠️ Unable to generate response. API key missing."
    system_prompt = f"""
    You are a Debate Partner Bot 🎤. 
    Your role is to always take the OPPOSITE stance of the user. 
    Debate style: {style}.
    Be respectful, logical, and engaging.

    ⚠ Important: Keep responses short (2–5 lines max). 
    Always finish with a complete thought or closing sentence. 
    Never leave the response hanging or incomplete.
    """
    messages = [
        {"role": "system", "content": system_prompt},
        {"role": "user", "content": user_message},
    ]
    response = client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=messages,
        temperature=0.7,
        max_tokens=40,
        stream=False,
    )
    return response.choices[0].message.content

@st.cache_data(show_spinner=False)
def generate_conclusion_cached(api_key: str, messages: List[Dict[str, str]]):
    client = get_groq_client_cached(api_key)
    if not client:
        return "⚠️ Unable to generate conclusion. API key missing."
    debate_text = "\n".join([f"{m['role'].capitalize()}: {m['content']}" for m in messages])
    system_prompt = """
    You are a Debate Summarizer Bot 📝.
    Your job is to read the entire debate and give a short, balanced conclusion (3–5 lines).
    Be neutral, fair, and ensure the conclusion feels like a proper ending.
    """
    response = client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": debate_text},
        ],
        temperature=0.7,
        max_tokens=150,
    )
    return response.choices[0].message.content

def main():
    st.set_page_config(page_title="Debate Partner Bot", page_icon="🎤", layout="wide")
    init_state()

    st.markdown("""
    <div style='text-align:center; padding:20px; background-color:#f0f8ff; border-radius:10px;'>
        <h1 style='color:#333;'>🎤 Welcome to Debate Partner Bot</h1>
        <p style='font-size:18px;'>Challenge your ideas. Sharpen your thinking. Debate with AI.</p>
    </div>
    """, unsafe_allow_html=True)

    with st.sidebar:
        st.header("👤 User Info")
        if st.session_state.user_name:
            st.write(f"Name: {st.session_state.user_name}")
        if st.session_state.user_email:
            st.write(f"Email: {st.session_state.user_email}")
        if st.session_state.debate_topic:
            st.write(f"Topic: {st.session_state.debate_topic}")
        if st.session_state.debate_style:
            st.write(f"Style: {st.session_state.debate_style}")
        st.markdown("---")
        st.header("⚙ Debate Controls")
        if st.button("📄 Download Debate as PDF"):
            pdf_buffer = generate_pdf(st.session_state.messages)
            st.download_button("⬇ Save PDF", data=pdf_buffer, file_name="debate.pdf", mime="application/pdf")
        if st.button("🛑 End Debate with Conclusion"):
            if st.session_state.messages:
                with st.spinner("Summarizing debate..."):
                    conclusion = generate_conclusion_cached(GROQ_API_KEY, st.session_state.messages)
                    st.session_state.conclusion = conclusion
                    st.session_state.messages.append({"role": "assistant", "content": f"📝 Conclusion: {conclusion}"})
            st.session_state.debate_active = False
        if st.button("🧹 Clear History"):
            st.session_state.messages = []
            st.session_state.conclusion = None
            st.session_state.debate_active = False
            st.success("Chat history cleared ✅")

        with st.sidebar.expander("💡 Debate Tips", expanded=False):
            st.write("""
            - Keep your arguments clear and concise.
            - Always be respectful and logical.
            - Try different debate styles for variety.
            - Use voice input for convenience (if enabled).
            - End the debate to receive a summary.
            """)

    col1, col2 = st.columns([3, 1])

    with col1:
        if not st.session_state.debate_active and not st.session_state.conclusion:
            with st.form("onboarding_form"):
                st.subheader("👤 Enter your details to start debating:")
                name = st.text_input("Your Name")
                email = st.text_input("Email")
                topic = st.text_input("Debate Topic", placeholder="e.g., AI is good for humanity")
                style = st.selectbox("Debate Style", ["Formal", "Casual", "Academic", "Friendly"])
                start_btn = st.form_submit_button("Start Debate 🎯")

                if start_btn:
                    if not name or not email or not topic:
                        st.error("⚠ Please fill in all details before starting.")
                    else:
                        st.session_state.user_name = name
                        st.session_state.user_email = email
                        st.session_state.debate_topic = topic
                        st.session_state.debate_style = style
                        st.session_state.debate_active = True
                        st.session_state.messages.append({
                            "role": "assistant",
                            "content": "🎯 Let's begin! Share your first argument and I'll challenge it."
                        })
                        st.success(f"Welcome {name}! Debate started on: {topic}")

        if st.session_state.debate_active:
            st.session_state.messages = st.session_state.messages[-20:]

            for msg in st.session_state.messages:
                with st.chat_message(msg["role"]):
                    st.markdown(msg["content"])

            prompt = st.chat_input("Enter your argument...")

            if prompt and not st.session_state.is_processing:
                st.session_state.is_processing = True
                st.session_state.messages.append({"role": "user", "content": prompt})

                with st.chat_message("user"):
                    st.markdown(prompt)

                with st.chat_message("assistant"):
                    with st.spinner("🤖 Generating counter-argument..."):
                        response = generate_opposite_response_cached(
                            GROQ_API_KEY,
                            prompt,
                            st.session_state.debate_style
                        )
                    st.markdown(response)

                st.session_state.messages.append({"role": "assistant", "content": response})
                st.session_state.is_processing = False

        if st.session_state.conclusion and not st.session_state.debate_active:
            st.subheader("📌 Debate Conclusion")
            st.info(st.session_state.conclusion)

    with col2:
        st.markdown("### 📊 Debate Stats (Coming Soon)")
        st.write("Track your debate length, number of turns, and sentiment analysis in future updates!")

# ✅ Entry point
if __name__ == "__main__":
    main()